filter:
  dependency_paths:
    - 'vendor/'
  excluded_paths:
    - 'tests/'
    - 'tools/'

build:
  dependencies:
    override:
      - composer update --no-interaction --no-progress --prefer-dist
  nodes:
    analysis: # see https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/
      environment:
        php:
          version: 7.4
      project_setup: { override: true }
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - command: php -dzend_extension=xdebug.so -dxdebug.mode=coverage vendor/bin/phpunit --verbose --testdox --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: clover
